package root
//
//
//
//
import hrf.colmat._
import hrf.logger._
//
//
//
//

// French display language for Root (the Language setting, FrenchLanguage in meta.scala).
//
// Only the display changes: hrf.elem.Translation passes every piece of text and every image id
// through text and image below when it is drawn, so games, saved moves and online games are the
// same in both languages and each player can pick theirs, even in the middle of a game.
//
// Text is translated piece by piece, the way the game builds it (a log line is "Marquise de Cat",
// "moved", "3", "Cats", "from", ...): words looks a whole piece up, and failing that, terms are
// replaced inside it. Terms follow the official French edition (Matagot), as printed on the French
// cards and faction boards from the TTS mod "Root FR" (Steam workshop 1829904481); the images
// are cut by root/tools/french-assets.py. Anything not listed stays in English.
object French {
    // whole pieces of text, without their surrounding spaces and final punctuation
    val words = Map[String, String](
        // phases and turns
        "Birdsong" -> "Aurore",
        "Daylight" -> "Jour",
        "Evening" -> "Crépuscule",
        "Night" -> "Nuit",
        "Turn" -> "Tour",
        "turn" -> "tour",
        "Turn #" -> "Tour n°",
        "End Turn" -> "Finir le tour",
        "End" -> "Fin",
        "End of" -> "Fin de",
        "Start of" -> "Début de",
        "Setup" -> "Mise en place",
        "setup" -> "mise en place",
        "On Setup" -> "À la mise en place",
        "on setup" -> "à la mise en place",
        "sets up" -> "se met en place",
        "Game Over" -> "Fin de la partie",
        "won" -> "a gagné",
        "Coalition" -> "Coalition",

        // suits
        "Fox" -> "Renard",
        "Rabbit" -> "Lapin",
        "Mouse" -> "Souris",
        "Bird" -> "Oiseau",
        "Frog" -> "Grenouille",
        "fox" -> "renard",
        "rabbit" -> "lapin",
        "mouse" -> "souris",
        "bird" -> "oiseau",
        "frog" -> "grenouille",
        "Foxes" -> "Renards",
        "Rabbits" -> "Lapins",
        "Mice" -> "Souris",
        "Birds" -> "Oiseaux",
        "Frogs" -> "Grenouilles",
        "Any" -> "N'importe laquelle",
        "No Suit" -> "Sans couleur",
        "suit" -> "couleur",

        // factions
        "Marquise de Cat" -> "Marquise de Chat",
        "Eyrie Dynasties" -> "Dynastie de la Canopée",
        "Woodland Alliance" -> "Alliance de la Forêt",
        "Vagabond" -> "Vagabond",
        "Riverfolk Company" -> "Compagnie de la Rivière",
        "The Lizard Cult" -> "Culte des Lézards",
        "Lizard Cult" -> "Culte des Lézards",
        "Underground Duchy" -> "Duché Souterrain",
        "Corvid Conspiracy" -> "Conspiration des Corvidés",
        "Lord of the Hundreds" -> "Seigneur des Cent",
        "Keepers in Iron" -> "Gardiens de Fer",
        "Factions" -> "Factions",
        "faction" -> "faction",
        "Choose faction" -> "Choisissez une faction",
        "Drawn factions" -> "Factions tirées",
        "Play as" -> "Jouer",

        // pieces
        "warrior" -> "guerrier",
        "warriors" -> "guerriers",
        "Warrior" -> "Guerrier",
        "Warriors" -> "Guerriers",
        "building" -> "bâtiment",
        "buildings" -> "bâtiments",
        "Buildings" -> "Bâtiments",
        "token" -> "jeton",
        "tokens" -> "jetons",
        "piece" -> "pièce",
        "pieces" -> "pièces",
        "Cat" -> "Chat",
        "Cats" -> "Chats",
        "cats" -> "chats",
        "Hawk" -> "Faucon",
        "Hawks" -> "Faucons",
        "birds" -> "oiseaux",
        "Critter" -> "Bestiole",
        "Critters" -> "Bestioles",
        "Otter" -> "Loutre",
        "Otters" -> "Loutres",
        "otters" -> "loutres",
        "Lizard" -> "Lézard",
        "Lizards" -> "Lézards",
        "lizards" -> "lézards",
        "Mole" -> "Taupe",
        "Moles" -> "Taupes",
        "moles" -> "taupes",
        "Raven" -> "Corbeau",
        "Ravens" -> "Corbeaux",
        "crows" -> "corbeaux",
        "Rat" -> "Rat",
        "Rats" -> "Rats",
        "Badger" -> "Blaireau",
        "Badgers" -> "Blaireaux",
        "Keep" -> "Donjon",
        "Wood" -> "Bois",
        "wood" -> "bois",
        "Sawmill" -> "Scierie",
        "Sawmills" -> "Scieries",
        "Workshop" -> "Atelier",
        "Workshops" -> "Ateliers",
        "Recruiter" -> "Recruteur",
        "Recruiters" -> "Recruteurs",
        "Roost" -> "Perchoir",
        "Roosts" -> "Perchoirs",
        "Sympathy" -> "Sympathie",
        "Base" -> "Base",
        "Bases" -> "Bases",
        "Trade Post" -> "Comptoir",
        "Trade Posts" -> "Comptoirs",
        "Garden" -> "Jardin",
        "Gardens" -> "Jardins",
        "Citadel" -> "Citadelle",
        "Citadels" -> "Citadelles",
        "Market" -> "Marché",
        "Markets" -> "Marchés",
        "Tunnel" -> "Tunnel",
        "Tunnels" -> "Tunnels",
        "Plot" -> "Complot",
        "Plots" -> "Complots",
        "Bomb" -> "Bombe",
        "Bombs" -> "Bombes",
        "Snare" -> "Piège",
        "Extortion" -> "Extorsion",
        "Raid" -> "Raffle",
        "Stronghold" -> "Place forte",
        "Strongholds" -> "Places fortes",
        "Waystation" -> "Relais",
        "Relic" -> "Relique",
        "Relics" -> "Reliques",
        "Ruins" -> "Ruines",
        "ruins" -> "ruines",

        // items
        "Items" -> "Objets",
        "items" -> "objets",
        "item" -> "objet",
        "Teapot" -> "Café",
        "Boots" -> "Bottes",
        "Sword" -> "Épée",
        "Torch" -> "Torche",
        "Crossbow" -> "Arbalète",
        "Hammer" -> "Marteau",
        "Coins" -> "Pièces",
        "Bag" -> "Sac",
        "Club" -> "Gourdin",
        "damaged" -> "endommagé",
        "exhausted" -> "épuisé",

        // the map
        "map" -> "plateau",
        "Map" -> "Plateau",
        "Maps" -> "Plateaux",
        "clearing" -> "clairière",
        "clearings" -> "clairières",
        "Clearings" -> "Clairières",
        "forest" -> "forêt",
        "Forest" -> "Forêt",
        "path" -> "chemin",
        "river" -> "rivière",
        "Autumn" -> "Automne",
        "Winter" -> "Hiver",
        "Lake" -> "Lac",
        "Path between" -> "Chemin entre",
        "path between" -> "chemin entre",

        // cards
        "card" -> "carte",
        "cards" -> "cartes",
        "Card" -> "Carte",
        "Cards" -> "Cartes",
        "deck" -> "pioche",
        "Deck" -> "Pioche",
        "hand" -> "main",
        "Hand" -> "Main",
        "Hand:" -> "Main :",
        "Hand: no cards" -> "Main : aucune carte",
        "No cards in hand." -> "Aucune carte en main.",
        "in hand." -> "en main.",
        "Discard pile" -> "Défausse",
        "Discard Pile" -> "Défausse",
        "Draw Deck" -> "Pioche",
        "pile" -> "défausse",
        "Ambush" -> "Embuscade",
        "Ambush!" -> "Embuscade !",
        "Dominance" -> "Domination",
        "dominances" -> "dominations",
        "Frog Dominance" -> "Domination Grenouille",
        "no cards" -> "aucune carte",
        "no matching cards" -> "aucune carte correspondante",
        "no matching card" -> "aucune carte correspondante",
        "1 Card" -> "1 carte",
        "The discard pile was shuffled" -> "La défausse a été mélangée",
        "The shared deck was shuffled" -> "La pioche a été mélangée",
        "down to hand limit" -> "jusqu'à la limite de main",
        "due to hand limit" -> "à cause de la limite de main",
        "to hand limit" -> "jusqu'à la limite de main",

        // card names: base deck
        "Birdy Bindle" -> "Baluchon",
        "Woodland Runners" -> "Coureur des bois",
        "Arms Trader" -> "Marchand d'armes",
        "Gently Used Knapsack" -> "Sac en bon état",
        "Root Tea" -> "Café chaud",
        "Travel Gear" -> "Attirail de voyage",
        "Protection Racket" -> "Protection payante",
        "Foxfolk Steel" -> "Acier des Renards",
        "Anvil" -> "Enclume",
        "Smuggler's Trail" -> "Contrebandiers",
        "A Visit to Friends" -> "Visite à des amis",
        "Bake Sale" -> "Vente de gâteaux",
        "Mouse-in-a-Sack" -> "Sac de souris",
        "Investments" -> "Investissements",
        "Armorers" -> "Armurier",
        "Sappers" -> "Sapeurs",
        "Brutal Tactics" -> "Tactiques brutales",
        "Royal Claim" -> "Requête royale",
        "Stand and Deliver!" -> "La bourse ou la vie !",
        "Stand and Deliver" -> "La bourse ou la vie",
        "Tax Collector" -> "Percepteur d'impôts",
        "Favor of the Foxes" -> "Faveur des Renards",
        "Favor of the Rabbits" -> "Faveur des Lapins",
        "Favor of the Mice" -> "Faveur des Souris",
        "Command Warren" -> "Chef de garenne",
        "Better Burrow Bank" -> "Banque des terriers",
        "Cobbler" -> "Cordonnier",
        "Scouting Party" -> "Groupe d'éclaireurs",
        "Codebreakers" -> "Décodeurs",
        "Fox Ambush!" -> "Embuscade Renard !",
        "Rabbit Ambush!" -> "Embuscade Lapin !",
        "Mouse Ambush!" -> "Embuscade Souris !",
        "Bird Ambush!" -> "Embuscade Oiseau !",
        "Fox Dominance" -> "Domination Renard",
        "Rabbit Dominance" -> "Domination Lapin",
        "Mouse Dominance" -> "Domination Souris",
        "Bird Dominance" -> "Domination Oiseau",

        // card names: Exiles and Partisans deck
        "Saboteurs" -> "Saboteurs",
        "Soup Kitchens" -> "Soupe populaire",
        "Boat Builders" -> "Canotier",
        "Corvid Planners" -> "Mécène Corbeau",
        "Eyrie Émigré" -> "Émigré de la Canopée",
        "Partisans" -> "Partisans",
        "Fox Partisans" -> "Partisans Renards",
        "Rabbit Partisans" -> "Partisans Lapins",
        "Mouse Partisans" -> "Partisans Souris",
        "Propaganda Bureau" -> "Propagande",
        "False Orders" -> "Ordres falsifiés",
        "Informants" -> "Informateurs",
        "Charm Offensive" -> "Opération séduction",
        "Coffin Makers" -> "Croquemort",
        "Swap Meet" -> "Marchandage",
        "League of Adventurous Mice" -> "Ligue des Souris Aventurières",
        "Murine Brokers" -> "Brocanteur",
        "Murine Broker" -> "Brocanteur",
        "Master Engravers" -> "Maître artisan",

        // actions
        "Move" -> "Déplacer",
        "move" -> "déplacer",
        "Battle" -> "Combattre",
        "battle" -> "combattre",
        "Recruit" -> "Recruter",
        "Build" -> "Construire",
        "build" -> "construire",
        "Craft" -> "Fabriquer",
        "craft" -> "fabriquer",
        "Draw" -> "Piocher",
        "Draw Cards" -> "Piocher des cartes",
        "Discard" -> "Défausser",
        "discard" -> "défausser",
        "Place" -> "Placer",
        "Remove" -> "Retirer",
        "remove" -> "retirer",
        "Take" -> "Prendre",
        "Skip" -> "Passer",
        "skip" -> "passer",
        "Done" -> "Terminé",
        "Cancel" -> "Annuler",
        "Continue" -> "Continuer",
        "Ok" -> "OK",
        "None" -> "Aucun",
        "Random" -> "Au hasard",
        "Start" -> "Commencer",
        "Reveal" -> "Révéler",
        "Score" -> "Marquer",
        "Activate" -> "Activer",
        "Add" -> "Ajouter",
        "Buy" -> "Acheter",
        "Repair" -> "Réparer",
        "Explore" -> "Explorer",
        "Aid" -> "Aider",
        "Quest" -> "Quête",
        "Quests" -> "Quêtes",
        "Strike" -> "Frapper",
        "Slip" -> "Se faufiler",
        "Refresh" -> "Rafraîchir",
        "Rest" -> "Se reposer",
        "Extra action" -> "Action supplémentaire",
        "extra action" -> "action supplémentaire",
        "Assign Hits" -> "Répartir les pertes",
        "Hits" -> "Pertes",
        "hits" -> "pertes",
        "hit" -> "perte",
        "End Anyway" -> "Finir quand même",
        "More Info" -> "Plus d'infos",
        "Less Info" -> "Moins d'infos",

        // log verbs and words
        "in" -> "dans",
        "with" -> "avec",
        "from" -> "de",
        "to" -> "vers",
        "and" -> "et",
        "or" -> "ou",
        "for" -> "pour",
        "of" -> "de",
        "as" -> "comme",
        "on" -> "sur",
        "by" -> "par",
        "the" -> "le",
        "The" -> "Le",
        "a" -> "un",
        "an" -> "un",
        "then" -> "puis",
        "and then" -> "puis",
        "is a" -> "est un",
        "are" -> "sont",
        "was" -> "était",
        "it" -> "le",
        "they" -> "ils",
        "each" -> "chaque",
        "all" -> "tous",
        "any" -> "n'importe quel",
        "no" -> "aucun",
        "one" -> "un",
        "two" -> "deux",
        "three" -> "trois",
        "four" -> "quatre",
        "zero" -> "zéro",
        "between" -> "entre",
        "instead of" -> "au lieu de",
        "due to" -> "à cause de",
        "once per turn" -> "une fois par tour",
        "up to" -> "jusqu'à",
        "maximum" -> "maximum",
        "max" -> "max",
        "free" -> "gratuit",
        "empty" -> "vide",
        "available" -> "disponible",
        "on the map" -> "sur le plateau",
        "on the map," -> "sur le plateau,",
        "in reserve" -> "en réserve",
        "in battle" -> "en combat",
        "in the" -> "dans le",
        "placed" -> "a placé",
        "places" -> "place",
        "can't place" -> "ne peut pas placer",
        "moved" -> "a déplacé",
        "moved with" -> "s'est déplacé avec",
        "can't move" -> "ne peut pas se déplacer",
        "battled" -> "a combattu",
        "battles" -> "combat",
        "recruited" -> "a recruté",
        "recruits" -> "recrute",
        "recruiting" -> "recrute",
        "recruited in" -> "a recruté dans",
        "Recruit in" -> "Recruter dans",
        "built" -> "a construit",
        "crafted" -> "a fabriqué",
        "crafting" -> "fabrication",
        "drew" -> "a pioché",
        "drawn" -> "pioché",
        "discarded" -> "a défaussé",
        "and discarded" -> "et a défaussé",
        "and discard" -> "et défausse",
        "discards" -> "défausse",
        "removed" -> "a retiré",
        "removing" -> "retirant",
        "took" -> "a pris",
        "took a card from" -> "a pris une carte à",
        "stole a card from" -> "a volé une carte à",
        "gave" -> "a donné",
        "got" -> "a obtenu",
        "gained" -> "a gagné",
        "lost" -> "a perdu",
        "used" -> "a utilisé",
        "played" -> "a joué",
        "revealed" -> "a révélé",
        "revealing" -> "révélant",
        "explored" -> "a exploré",
        "repaired" -> "a réparé",
        "aided" -> "a aidé",
        "aiding" -> "aidant",
        "achieved" -> "a réalisé",
        "became" -> "est devenu",
        "rolled" -> "a obtenu",
        "rolled the" -> "a lancé le",
        "scored" -> "a marqué",
        "scores" -> "marque",
        "and scored" -> "et a marqué",
        "for each" -> "pour chaque",
        "ruled" -> "contrôlée",
        "rule" -> "contrôle",
        "rules" -> "contrôle",
        "controller" -> "contrôleur",
        "hired" -> "a engagé",
        "returned" -> "est revenu",
        "flipped" -> "a retourné",
        "flipping" -> "retournant",
        "exploded" -> "a explosé",
        "captured" -> "a capturé",
        "added" -> "a ajouté",
        "started in" -> "a commencé dans",
        "starts in" -> "commence dans",
        "start" -> "début",
        "dealt an extra" -> "a infligé une perte supplémentaire",
        "Deal an extra" -> "Infliger une perte supplémentaire",
        "to deal an extra" -> "pour infliger une perte supplémentaire",
        "attacked with" -> "a attaqué avec",
        "defended" -> "a défendu",
        "was defenseless" -> "était sans défense",
        "Ambush with" -> "Embuscade avec",
        "Counter-Ambush with" -> "Contre-embuscade avec",
        "Counter-Ambush" -> "Contre-embuscade",
        "Battle with" -> "Combat avec",
        "Battle ended in" -> "Le combat s'est terminé dans",
        "can't battle in" -> "ne peut pas combattre dans",
        "no enemies" -> "aucun ennemi",
        "no warriors" -> "aucun guerrier",
        "no targets" -> "aucune cible",
        "no target" -> "aucune cible",
        "no items" -> "aucun objet",
        "nothing craftable" -> "rien à fabriquer",
        "not enough wood" -> "pas assez de bois",
        "Defender" -> "Défenseur",
        "victory point" -> "point de victoire",
        "victory points" -> "points de victoire",
        "VP" -> "PV",
        "vp" -> "PV",
        "2 VP" -> "2 PV",
        "Good Game" -> "Bien joué",

        // Marquise de Chat
        "Field Hospitals" -> "Hôpitaux de campagne",
        "Overwork" -> "Surmenage",
        "overworked in" -> "a surmené dans",
        "March" -> "Marche",
        "produced" -> "a produit",
        "no workshops" -> "aucun atelier",
        "no sawmills" -> "aucune scierie",
        "no recruiters" -> "aucun recruteur",

        // Dynastie de la Canopée
        "Decree" -> "Décret",
        "Turmoil" -> "Crise",
        "turmoil" -> "crise",
        "Leader" -> "Dirigeant",
        "leader" -> "dirigeant",
        "Builder" -> "Bâtisseur",
        "Charismatic" -> "Charismatique",
        "Commander" -> "Commandant",
        "Despot" -> "Despote",
        "Loyal Vizier" -> "Vizir loyal",
        "viziers" -> "vizirs",
        "Disdain for Trade" -> "Mépris du commerce",
        "Lords of the Forest" -> "Seigneur de la Forêt",
        "Resolve" -> "Résoudre",
        "Execute" -> "Résoudre",
        "Add to" -> "Ajouter au",
        "issued" -> "a ajouté au Décret",

        // Alliance de la Forêt
        "Revolt" -> "Révolte",
        "No Revolt" -> "Pas de Révolte",
        "Spread Sympathy" -> "Gagner la Sympathie",
        "Spread" -> "Gagner la Sympathie",
        "No Spread Sympathy" -> "Pas de Sympathie",
        "spreads" -> "gagne la Sympathie",
        "spread" -> "a gagné la Sympathie",
        "Mobilize" -> "Mobilisation",
        "mobilized" -> "a mobilisé",
        "Train" -> "Entraînement",
        "trained" -> "a entraîné",
        "Organize" -> "Organisation",
        "organized" -> "a organisé",
        "Officer" -> "Officier",
        "Officers" -> "Officiers",
        "officer" -> "officier",
        "Supporters" -> "Partisans",
        "supporters" -> "partisans",
        "Supporter" -> "Partisan",
        "Supporters:" -> "Partisans :",
        "Outrage" -> "Indignation",
        "Guerilla Tactics" -> "Guérilla",
        "Guerrilla War" -> "Guérilla",

        // Vagabond
        "Thief" -> "Voleur",
        "Tinker" -> "Bricoleur",
        "Ranger" -> "Rôdeur",
        "Arbiter" -> "Arbitre",
        "Scoundrel" -> "Scélérat",
        "Vagrant" -> "Vagabond",
        "Harrier" -> "Messager",
        "Ronin" -> "Ronin",
        "Adventurer" -> "Aventurier",
        "Steal" -> "Voler",
        "Day Labor" -> "Journalier",
        "Hideout" -> "Planque",
        "Protector" -> "Protecteur",
        "Nimble" -> "Agile",
        "Lone Wanderer" -> "Voyageur solitaire",
        "Hostile" -> "Hostile",
        "hostile" -> "hostile",
        "Allied" -> "Allié",
        "Indifferent" -> "Indifférent",
        "Satchel" -> "Sacoche",
        "Errand" -> "Course",
        "Escort" -> "Escorte",
        "Give a Speech" -> "Faire un discours",
        "Guard Duty" -> "Tour de garde",
        "Expel Bandits" -> "Chasser les bandits",
        "Fend off a Bear" -> "Repousser un ours",
        "Fundraising" -> "Collecte de fonds",
        "Logistic Help" -> "Aide logistique",
        "Repair a Shed" -> "Réparer une cabane",

        // Compagnie de la Rivière
        "Protectionism" -> "Protectionnisme",
        "Payments" -> "Paiements",
        "Funds" -> "Fonds",
        "funds" -> "fonds",
        "Commitments" -> "Investissements",
        "Services" -> "Services",
        "services" -> "services",
        "Riverboats" -> "Bateaux",
        "Mercenaries" -> "Mercenaires",
        "Swimmers" -> "Nageurs",
        "Buy Card" -> "Acheter une carte",
        "Export" -> "Exporter",

        // Culte des Lézards
        "Acolytes" -> "Acolytes",
        "Lost Souls" -> "Âmes Perdues",
        "Outcast" -> "Parias",
        "Hated Outcast" -> "Paria haï",
        "Conspiracies" -> "Conspirations",
        "Convert" -> "Conversion",
        "Crusade" -> "Croisade",
        "Sanctify" -> "Sanctuaire",
        "Ritual" -> "Rituel",
        "Rituals" -> "Rituels",
        "Sacrifice" -> "Sacrifice",
        "Revenge" -> "Vengeance",
        "Hatred" -> "Haine des Oiseaux",
        "Pilgrims" -> "Pèlerins",

        // Conspiration des Corvidés
        "Embedded Agents" -> "Agents infiltrés",
        "Exposure" -> "Divulgation",
        "Expose" -> "Divulguer",
        "Trick" -> "Subterfuge",
        "Flip" -> "Retourner",

        // Duché Souterrain
        "Burrow" -> "Terrier",
        "Dig" -> "Creuser",
        "Minister" -> "Ministre",
        "Ministers" -> "Ministres",
        "ministers" -> "ministres",
        "Sway" -> "Influencer",
        "Squire" -> "Châtelain",
        "Noble" -> "Noble",
        "Lord" -> "Seigneur",
        "Price of Failure" -> "Le Prix de l'Échec",

        // menus and setup
        "Quick Game" -> "Partie rapide",
        "Local Game" -> "Partie locale",
        "Play Online" -> "Jouer en ligne",
        "Custom Game" -> "Partie personnalisée",
        "Back" -> "Retour",
        "Options" -> "Options",
        "Interface" -> "Interface",
        "Settings" -> "Réglages",
        "Language" -> "Langue",
        "Rules" -> "Règles",
        "About" -> "À propos",
        "Players" -> "Joueurs",
        "Player" -> "Joueur",
        "Seating" -> "Ordre du tour",
        "Standard" -> "Standard",
        "Advanced Setup" -> "Mise en place avancée",
        "Mirror" -> "Miroir",
        "Easy" -> "Facile",
        "Normal" -> "Normal",
        "Hard" -> "Difficile",
        "Human" -> "Humain",
        "Bot" -> "Robot",
        "Log" -> "Journal",
        "log" -> "journal",
        "Report a Bug" -> "Signaler un bug",
        "Undo" -> "Annuler",
        "Reset All Settings" -> "Réinitialiser les réglages",
        "Save Game Online" -> "Sauvegarder la partie en ligne",
        "Official" -> "Officiel",
        "Homeland" -> "Homeland",
        "Stacked" -> "Empilés",
        "Separate" -> "Séparés",
        "Shown" -> "Affichés",
        "Hidden" -> "Masqués",
        "Card Piles" -> "Piles de cartes",
        "Pond" -> "Mare",
        "Side Panel" -> "Panneau latéral",
        "On the Map" -> "Sur le plateau",
        " (Draw, Discard, Pond, Lost Souls and Dominances)" -> " (pioche, défausse, mare, âmes perdues et dominations)",

        // more menus and setup
        "Play" -> "Jouer",
        "Hotseat" -> "à plusieurs sur un écran",
        "Select at least two factions" -> "Choisissez au moins deux factions",
        "Start Setup" -> "Commencer la mise en place",
        "Setup Factions" -> "Factions",
        "Start Game" -> "Commencer la partie",
        "Next" -> "Suivant",
        "Presets" -> "Préréglages",
        "Reset Options" -> "Réinitialiser les options",
        "Other" -> "Autres",
        "Recent Games" -> "Parties récentes",
        "New Local Game" -> "Nouvelle partie locale",
        "New Online Game" -> "Nouvelle partie en ligne",
        "New Quick Game" -> "Nouvelle partie rapide",
        "Player Links" -> "Liens des joueurs",
        "Spectator Link" -> "Lien spectateur",
        "Copy all links" -> "Copier tous les liens",
        "Loading assets" -> "Chargement",
        "Notifications" -> "Notifications",
        "On" -> "Activé",
        "Off" -> "Désactivé",
        "Reach" -> "Atteindre",
        "Landmarks" -> "Lieux",
        "Default" -> "Par défaut",
        "Map Default" -> "Selon le plateau",
        "All Random" -> "Tout au hasard",
        "Mirror Factions" -> "Factions miroir",
        "Fun Factions" -> "Factions amusantes",
        "Available Factions" -> "Factions disponibles",
        "Order Given" -> "Ordre donné",
        "Card Draft" -> "Draft de cartes",
        "Friends and Favors" -> "Amis et Faveurs",
        "Exiles and Partisans" -> "Exilés et Partisans",
        "Mixed" -> "Mélangée",
        "Choose character" -> "Choisissez un personnage",
        "Random character" -> "Personnage au hasard",
        "get a new leader" -> "choisit un nouveau dirigeant",
        "started with" -> "a commencé avec",
        "and six" -> "et six",
        "through the forest" -> "à travers la forêt",
        "drew from the deck" -> "a pioché",
        "crafts" -> "fabrique",
        "End Craft" -> "Finir la fabrication",
        "Full" -> "Plein",
        "Double recruting" -> "Double recrutement",
        "Extra" -> "+1",
        "attacking" -> "en attaque",
        "destroying" -> "en détruisant",
        // names that stay in English (not official, or the same word): listed so their parts aren't translated
        "Forest Union" -> "Forest Union",
        "Raven Innocence" -> "Raven Innocence",
        "Perching Emirates" -> "Perching Emirates",
        "Baron von Katze" -> "Baron von Katze",
        "Crocodile Monks" -> "Crocodile Monks",
        "Deep Realm" -> "Deep Realm",
        "Longtail Kaliph" -> "Longtail Kaliph",
        "Friend of the Forest" -> "Friend of the Forest",
        "Forest Patrol" -> "Forest Patrol",
        "Mole Artisians" -> "Mole Artisians",
        "Stoic Protector" -> "Stoic Protector",
    )

    // names and game terms, also replaced inside longer pieces of text (longest first, whole words)
    val terms = words.filter { case (k, v) => k.length > 3 && k.head.isUpper && k != v && k.exists(_.isLower) }

    private val pattern = {
        def quote(s : String) = s.flatMap(c => if ("\\^$.|?*+()[]{}".contains(c)) "\\" + c else c.toString)
        java.util.regex.Pattern.compile("\\b(" + terms.keys.toList.sortBy(-_.length).map(quote).mkString("|") + ")(?![\\w'])")
    }

    private val cache = scala.collection.mutable.HashMap[String, String]()

    private def lookup(s : String) : Option[String] = {
        words.get(s).orElse {
            if (s.head.isUpper)
                words.get(s.head.toLower + s.drop(1)).map(t => t.head.toUpper + t.drop(1))
            else
                None
        }
    }

    private def substitute(s : String) : String = {
        val m = pattern.matcher(s)
        val b = new StringBuilder
        var last = 0
        while (m.find()) {
            b ++= s.substring(last, m.start)
            b ++= terms(m.group(1))
            last = m.end
        }
        b ++= s.substring(last)
        b.toString
    }

    private def translate(s : String) : String = {
        val core = s.trim
        if (!core.exists(_.isLetter))
            return s

        val lead = s.takeWhile(_.isWhitespace)
        val trail = s.reverse.takeWhile(_.isWhitespace).reverse

        val punct = core.reverse.takeWhile(c => ".,:;!?)".contains(c)).reverse
        val open = core.takeWhile(_ == '(')
        val bare = core.drop(open.length).dropRight(punct.length)

        lookup(core).map(lead + _ + trail).orElse(
            (if (bare.nonEmpty) lookup(bare) else None).map(lead + open + _ + punct + trail)
        ).getOrElse(substitute(s))
    }

    def text(s : String) : String = cache.getOrElseUpdate(s, translate(s))

    // French card and faction board images (root/tools/french-assets.py; the Hundreds, Keepers, Lilypad, Council and Knaves boards
    // and newer copies of the others from a player on 2026-10-10), loaded on demand under "fr:"
    val cards = $(
        "armorers", "woodland-runners", "arms-trader", "bird-crossbow", "sappers", "brutal-tactics", "royal-claim",
        "fox-ambush", "gently-used-knapsack", "fox-root-tea", "fox-travel-gear", "protection-racket", "foxfolk-steel", "anvil", "stand-and-deliver", "tax-collector",
        "favor-of-the-foxes", "rabbit-ambush", "smugglers-trail", "rabbit-root-tea", "a-visit-to-friends", "bake-sale", "command-warren",
        "better-burrow-bank", "cobbler", "favor-of-the-rabbits", "mouse-ambush", "mouse-in-a-sack", "mouse-root-tea", "mouse-travel-gear", "investments",
        "sword", "mouse-crossbow", "scouting-party", "bird-ambush", "birdy-bindle", "bird-dominance", "fox-dominance", "codebreakers",
        "mouse-dominance", "favor-of-the-mice", "rabbit-dominance",
        "saboteurs", "soup-kitchens", "boat-builders", "corvid-planners", "eyrie-emigre", "fox-partisans", "propaganda-bureau", "false-orders", "informants",
        "rabbit-partisans", "tunnels", "charm-offensive", "coffin-makers", "swap-meet", "mouse-partisans", "league-of-adventurous-mice",
        "murine-broker", "master-engravers",
    )

    val boards = $("mc-board", "ed-board", "wa-board", "vb-board", "lc-board", "rf-board", "cc-board", "ud-board", "lh-board", "ki-board", "hld-board", "tc-board-h", "kd-board-h")

    private val images = (cards ++ boards).toSet

    def image(id : String) : String = if (images.contains(id.toLowerCase)) "fr:" + id.toLowerCase else id
}
