package nort
//
//
//
//
import hrf.colmat._
//
//
//
//

// Generated by nort/tools/ResourceIcons.java from the territory masks; do not edit by hand.
// The resource icons on each unturned tile: centre and radius, in tile units.
object TileIcons {
    case class Icon(x : Double, y : Double, r : Double)

    val icons : Map[String, $[Icon]] = Map(
        "start" -> $(),
        "start-5" -> $(Icon(0.209, 0.684, 0.064)),
        "tile-01" -> $(Icon(0.538, 0.269, 0.069)),
        "tile-02" -> $(Icon(0.330, 0.637, 0.072)),
        "tile-03" -> $(Icon(0.285, 0.486, 0.072)),
        "tile-04" -> $(),
        "tile-05" -> $(),
        "tile-06" -> $(Icon(0.200, 0.523, 0.077), Icon(0.640, 0.847, 0.079)),
        "tile-07" -> $(Icon(0.835, 0.627, 0.070)),
        "tile-08" -> $(),
        "tile-09" -> $(Icon(0.558, 0.107, 0.067)),
        "tile-10" -> $(Icon(0.596, 0.118, 0.070)),
        "tile-11" -> $(Icon(0.345, 0.163, 0.077)),
        "tile-12" -> $(Icon(0.183, 0.540, 0.076)),
        "tile-13" -> $(Icon(0.686, 0.728, 0.077)),
        "tile-14" -> $(Icon(0.439, 0.830, 0.073)),
        "tile-15" -> $(Icon(0.282, 0.844, 0.079)),
        "tile-16" -> $(Icon(0.529, 0.164, 0.074), Icon(0.642, 0.854, 0.079)),
        "tile-17" -> $(),
        "tile-18" -> $(Icon(0.400, 0.821, 0.075)),
        "tile-19" -> $(Icon(0.853, 0.310, 0.079)),
        "tile-20" -> $(Icon(0.259, 0.178, 0.071), Icon(0.542, 0.687, 0.079)),
        "tile-21" -> $(Icon(0.158, 0.312, 0.073)),
        "tile-22" -> $(Icon(0.572, 0.847, 0.078)),
        "tile-23" -> $(Icon(0.144, 0.569, 0.080)),
        "tile-24" -> $(),
        "tile-25" -> $(),
        "tile-26" -> $(Icon(0.436, 0.154, 0.073), Icon(0.595, 0.844, 0.077)),
        "tile-27" -> $(Icon(0.841, 0.274, 0.077)),
        "tile-28" -> $(Icon(0.740, 0.675, 0.077)),
        "tile-29" -> $(Icon(0.604, 0.166, 0.076)),
        "tile-30" -> $(Icon(0.743, 0.527, 0.076)),
        "tile-31" -> $(Icon(0.614, 0.851, 0.065)),
        "tile-32" -> $(Icon(0.821, 0.478, 0.074)),
        "tile-33" -> $(),
        "wild-lake" -> $(),
        "wild-geyser-1" -> $(),
        "wild-geyser-2" -> $(),
        "wild-ruins-1" -> $(Icon(0.473, 0.845, 0.079)),
        "wild-ruins-2" -> $(Icon(0.303, 0.767, 0.079)),
        "wild-swamp" -> $(),
        "wild-poison" -> $(),
        "wild-peaks-1" -> $(Icon(0.540, 0.165, 0.070)),
        "wild-peaks-2" -> $(Icon(0.540, 0.165, 0.070)),
        "wild-graveyard" -> $(),
        "wild-den" -> $(),
        "waste-kobold" -> $(),
        "waste-jotnar" -> $(Icon(0.497, 0.905, 0.055)),
        "waste-nastrond" -> $(Icon(0.094, 0.368, 0.072)),
        "waste-landvidi" -> $(),
        "waste-thor" -> $(),
        "waste-urdarbrunn" -> $(),
        "waste-vedrfolnir" -> $(),
        "start-magma" -> $(),
        "start-yggdrasil" -> $(),
        "start-relic" -> $(),
        "start-lake" -> $(),
        "start-volcano" -> $(),
        "start-mimir" -> $(),
        "start-hrimgandr" -> $(),
        "start-den" -> $(),
        "start-helheim" -> $(),
        "start-5-open" -> $(),
        "start-5-wall" -> $(),
        "horizon-1" -> $(),
        "horizon-2" -> $(Icon(0.301, 0.431, 0.071), Icon(0.666, 0.876, 0.067)),
        "horizon-3" -> $(Icon(0.733, 0.352, 0.029), Icon(0.488, 0.447, 0.067)),
        "horizon-4" -> $(Icon(0.441, 0.871, 0.066)),
        "horizon-bridge" -> $(Icon(0.480, 0.107, 0.065), Icon(0.076, 0.556, 0.071))
    )
}
