// Makes nort/lines.scala: the dashes of every border on the tile art, so the map can draw
// the borders of closed territories in their controllers' colours.
//
// The borders on the tiles are roads with white (regular) or yellow (rough) dashes. The dashes are
// found by colour, like in tile-masks.py; each one goes to the border between the two areas
// (webp2/nort/images/tile/mask/) found around it, and is stored as a rounded rectangle (centre,
// angle, length, width, in tile units), ordered along its border.
//
// Needs Java 11+ and ImageMagick (convert). Run from the repository root:
//   java haunt-roll-fail/nort/tools/BorderLines.java [--check DIR]
// --check writes an image per tile to DIR with the dashes found, coloured by border.
//
// It also traces the solid orange lines of the impassable borders (walls) that have a territory on
// each side (the Peaks, the Poisonous Swamp's corners, the five-player tile with walls), so the map
// can draw solid rails beside them when a side is controlled. The rings around impassable middles
// have a territory on one side only and are left out.

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.regex.*;

public class BorderLines {
    static final int N = 948;
    static Path root, nort, tiles, masks;
    // Tiles cut from a photo have washed-out colours, and the Wilderness tiles darker ones
    static final Set<String> PHOTO = Set.of("start-5", "tile-31", "tile-32", "tile-33");
    // Wastelands central tiles from the TTS scans: pale teal dashes
    static final Set<String> TEAL = Set.of("start-magma", "start-helheim", "start-relic");
    // Impassable middles inside an orange ring: their walls have no territory on the inside
    static final Set<String> RINGED = Set.of("start-relic", "start-lake", "start-volcano", "waste-kobold", "waste-jotnar", "waste-nastrond");
    // Beach tiles (Sea module): the shore's dashes are borders between each land area and the sea, whose mask
    // (<tile>-sea.webp, made by tile-masks.py) is read like an area's; the map colours only the land side
    static final Set<String> BEACH = Set.of("beach-port", "beach-wing-w", "beach-wing-e");

    // Tiles whose pale dashes the colour tests miss: their borders traced by hand in tools/traced-borders.json
    // (border "a-b" -> points); a light dash near a traced line belongs to that line's border
    static Map<String, Map<String, List<double[]>>> traced = new LinkedHashMap<>();

    static void readTraced() throws IOException {
        String js = Files.readString(nort.resolve("tools/traced-borders.json")).replaceAll("\\s", "");
        Matcher tm = Pattern.compile("\"([\\w-]+)\":\\{(.*?)\\}").matcher(js);
        while (tm.find()) {
            Map<String, List<double[]>> borders = new LinkedHashMap<>();
            Matcher bm = Pattern.compile("\"(\\w+-\\w+)\":\\[(.*?)\\]\\]").matcher(tm.group(2));
            while (bm.find()) {
                List<double[]> pts = new ArrayList<>();
                Matcher pm = Pattern.compile("\\[([-\\d.]+),([-\\d.]+)").matcher(bm.group(2) + "]");
                while (pm.find())
                    pts.add(new double[] { Double.parseDouble(pm.group(1)), Double.parseDouble(pm.group(2)) });
                borders.put(bm.group(1), pts);
            }
            traced.put(tm.group(1), borders);
        }
    }

    // Distance from x, y to a traced line, in tile units
    static double toLine(List<double[]> pts, double x, double y) {
        double best = 1e9;
        for (int i = 0; i + 1 < pts.size(); i++) {
            double[] p = pts.get(i), q = pts.get(i + 1);
            double dx = q[0] - p[0], dy = q[1] - p[1];
            double l = dx * dx + dy * dy;
            double u = l == 0 ? 0 : Math.max(0, Math.min(1, ((x - p[0]) * dx + (y - p[1]) * dy) / l));
            best = Math.min(best, Math.hypot(x - p[0] - u * dx, y - p[1] - u * dy));
        }
        return best;
    }

    record Border(String a, String b, boolean wall) {}
    record Tile(String id, List<String> areas, List<Border> borders) {}
    // A dash as a bent bar: its two ends and middle on its centre line, and its width
    record Dash(double x, double y, double angle, double length, double width, double[] line) {}

    public static void main(String[] args) throws Exception {
        root = Paths.get("haunt-roll-fail").toAbsolutePath();
        nort = root.resolve("nort");
        tiles = root.resolve("webp2/nort/images/tile");
        masks = tiles.resolve("mask");
        readTraced();
        String check = args.length >= 2 && args[0].equals("--check") ? args[1] : null;
        if (check != null)
            Files.createDirectories(Paths.get(check));

        StringBuilder out = new StringBuilder();
        out.append("package nort\n//\n//\n//\n//\nimport hrf.colmat._\n//\n//\n//\n//\n\n");
        out.append("// Generated by nort/tools/BorderLines.java from the tile art; do not edit by hand.\n");
        out.append("// The dashes of each border (not the Wilderness walls) on the unturned tile, in order along it:\n");
        out.append("// a bar through three points of its centre line (ends and middle), and its width, in ten thousandths of a tile.\n");
        out.append("object BorderLines {\n");
        out.append("    case class Dash(x0 : Double, y0 : Double, x1 : Double, y1 : Double, x2 : Double, y2 : Double, width : Double)\n\n");
        out.append("    case class Line(a : String, b : String, data : String) {\n");
        out.append("        lazy val dashes : $[Dash] = data.split(' ').toList.filter(_.nonEmpty).map(_.toInt / 10000.0).grouped(7).toList.map(v => Dash(v(0), v(1), v(2), v(3), v(4), v(5), v(6)))\n");
        out.append("    }\n\n");
        out.append("    val lines : Map[String, $[Line]] = Map(\n");

        StringBuilder wallOut = new StringBuilder();

        for (Tile t : parse()) {
            if (BEACH.contains(t.id)) {
                for (String a : List.copyOf(t.areas))
                    t.borders.add(new Border(a, "sea", false));
                t.areas.add("sea");
            }
            int[] rgb = readRaw(tiles.resolve(t.id + ".webp"), "rgb", 3);
            int[][] alpha = new int[t.areas.size()][];
            for (int k = 0; k < t.areas.size(); k++)
                alpha[k] = readRaw(masks.resolve(t.id + "-" + t.areas.get(k) + ".webp"), "alpha", 1);

            // Area of each pixel: the strongest mask
            int[] lab = new int[N * N];
            for (int i = 0; i < N * N; i++) {
                int best = -1, v = 30;
                for (int k = 0; k < alpha.length; k++)
                    if (alpha[k][i] > v) { v = alpha[k][i]; best = k; }
                lab[i] = best;
            }

            boolean[] dash = dashes(rgb, PHOTO.contains(t.id) || t.id.startsWith("wild-"), TEAL.contains(t.id));
            Map<String, List<double[]>> lines = traced.get(t.id);
            if (lines != null)
                for (int i = 0; i < N * N; i++) {
                    int r = rgb[i * 3], g = rgb[i * 3 + 1], b = rgb[i * 3 + 2];
                    int lo = Math.min(r, Math.min(g, b)), spread = Math.max(r, Math.max(g, b)) - lo;
                    boolean near = false;
                    if (lo > 95 && g > 150 && b >= r - 10 && spread < 90)
                        for (List<double[]> pts : lines.values())
                            if (toLine(pts, (i % N + 0.5) / N, (i / N + 0.5) / N) < 0.045) { near = true; break; }
                    dash[i] = near;
                }
            int[] comp = new int[N * N];
            List<int[]> comps = label(dash, comp);

            Map<Border, List<Dash>> found = new LinkedHashMap<>();
            Map<Border, List<int[]>> pixels = new LinkedHashMap<>();
            for (Border b : t.borders)
                if (!b.wall) { found.put(b, new ArrayList<>()); pixels.put(b, new ArrayList<>()); }

            for (int[] c : comps) {
                if (c.length < 20 || c.length > 1100)
                    continue;
                Dash f = fit(c);
                // Dashes are bars, some bent; skip thin lines (building space outlines) and round blobs
                if (f.width * N < 5 || f.width * N > 15 || f.length < f.width * 1.2)
                    continue;
                // Traced tiles: the border of the nearest traced line
                if (lines != null) {
                    // Only dash-sized bars: the snow and pale ground along the roads make long streaks
                    if (f.length * N > 32 || f.length * N < 12)
                        continue;
                    String key = null;
                    double best = 0.045;
                    for (var e : lines.entrySet()) {
                        double d = toLine(e.getValue(), f.x, f.y);
                        if (d < best) { best = d; key = e.getKey(); }
                    }
                    if (key == null)
                        continue;
                    String[] ab = key.split("-");
                    for (Border br : found.keySet())
                        if ((br.a.equals(ab[0]) && br.b.equals(ab[1])) || (br.a.equals(ab[1]) && br.b.equals(ab[0]))) {
                            found.get(br).add(f);
                            pixels.get(br).add(c);
                        }
                    continue;
                }
                // The two nearest areas (some masks of the Wilderness tiles stop short of the roads)
                double[] near = new double[t.areas.size()];
                Arrays.fill(near, 1e9);
                int r = 70;
                int cx = (int) (f.x * N), cy = (int) (f.y * N);
                for (int y = Math.max(0, cy - r); y < Math.min(N, cy + r); y++)
                    for (int x = Math.max(0, cx - r); x < Math.min(N, cx + r); x++)
                        if (lab[y * N + x] >= 0)
                            near[lab[y * N + x]] = Math.min(near[lab[y * N + x]], Math.hypot(x - cx, y - cy));
                Integer[] order = new Integer[near.length];
                for (int k = 0; k < order.length; k++) order[k] = k;
                Arrays.sort(order, (p, q) -> Double.compare(near[p], near[q]));
                if (order.length < 2 || near[order[1]] > r)
                    continue;
                String a = t.areas.get(order[0]), b = t.areas.get(order[1]);
                // Beach tiles: the areas on either side of the dash, across it (the sand, the sea and the holes in the
                // masks count as sea), since the sand makes the nearest areas misleading near the shore
                int sea = t.areas.indexOf("sea");
                if (sea >= 0) {
                    String[] side = new String[2];
                    double px = -Math.sin(f.angle), py = Math.cos(f.angle);
                    for (int k = 0; k < 2; k++) {
                        int[] votes = new int[t.areas.size()];
                        for (int d = 10; d <= 34; d += 3) {
                            int x = (int) (f.x * N + (k == 0 ? d : -d) * px), y = (int) (f.y * N + (k == 0 ? d : -d) * py);
                            if (x < 0 || y < 0 || x >= N || y >= N)
                                continue;
                            int i = y * N + x, rr = rgb[i * 3], gg = rgb[i * 3 + 1], bb = rgb[i * 3 + 2];
                            boolean sand = rr > 170 && gg > 160 && bb < 175 && rr - bb > 30 && Math.abs(rr - gg) < 40;
                            votes[sand || lab[i] < 0 ? sea : lab[i]]++;
                        }
                        int best = 0;
                        for (int v = 1; v < votes.length; v++) if (votes[v] > votes[best]) best = v;
                        side[k] = t.areas.get(best);
                    }
                    if (side[0].equals(side[1])) {
                        // Both sides alike (a wide road, sand on both, the Port's jetty): the nearest land beside the sea
                        if (!side[0].equals("sea") && near[sea] > 40)
                            continue;
                        a = t.areas.get(order[0] == sea ? order[1] : order[0]);
                        b = "sea";
                    }
                    else {
                        a = side[0];
                        b = side[1];
                    }
                }
                for (Border br : found.keySet())
                    if ((br.a.equals(a) && br.b.equals(b)) || (br.a.equals(b) && br.b.equals(a))) {
                        found.get(br).add(f);
                        pixels.get(br).add(c);
                    }
            }

            out.append("        \"" + t.id + "\" -> $(\n");
            for (Border b : found.keySet()) {
                List<Dash> ds = chain(found.get(b));
                StringBuilder data = new StringBuilder();
                for (Dash x : ds) {
                    for (double v : x.line)
                        data.append(Math.round(v * 10000)).append(' ');
                    data.append(Math.round(x.width * 10000)).append(' ');
                }
                out.append("            Line(\"" + b.a + "\", \"" + b.b + "\", \"" + data.toString().trim() + "\"),\n");
                if (ds.isEmpty())
                    System.err.println(t.id + ": no dashes for " + b.a + "-" + b.b);
            }
            out.append("        ),\n");

            Map<Border, List<List<double[]>>> walls = walls(t, rgb, lab);
            if (!walls.isEmpty()) {
                wallOut.append("        \"" + t.id + "\" -> $(\n");
                for (var e : walls.entrySet()) {
                    List<String> runs = new ArrayList<>();
                    for (List<double[]> run : e.getValue()) {
                        StringBuilder data = new StringBuilder();
                        for (double[] q : run)
                            data.append(Math.round(q[0] * 10000)).append(' ').append(Math.round(q[1] * 10000)).append(' ');
                        runs.add("\"" + data.toString().trim() + "\"");
                    }
                    wallOut.append("            Wall(\"" + e.getKey().a + "\", \"" + e.getKey().b + "\", $(" + String.join(", ", runs) + ")),\n");
                }
                wallOut.append("        ),\n");
            }

            if (check != null) {
                var im = new java.awt.image.BufferedImage(N, N, java.awt.image.BufferedImage.TYPE_INT_RGB);
                for (int i = 0; i < N * N; i++)
                    im.setRGB(i % N, i / N, (rgb[i * 3] / 2 << 16) | (rgb[i * 3 + 1] / 2 << 8) | rgb[i * 3 + 2] / 2);
                var g = im.createGraphics();
                g.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                java.awt.Color[] pal = {java.awt.Color.RED, java.awt.Color.BLUE, java.awt.Color.YELLOW, java.awt.Color.MAGENTA, java.awt.Color.GREEN, java.awt.Color.ORANGE, java.awt.Color.CYAN};
                int k = 0;
                for (Border b : found.keySet()) {
                    int j = 0;
                    for (Dash x : chain(found.get(b))) {
                        g.setColor(j++ % 2 == 0 ? pal[k % pal.length] : java.awt.Color.WHITE);
                        g.setStroke(new java.awt.BasicStroke((float) (x.width * N + 2), java.awt.BasicStroke.CAP_BUTT, java.awt.BasicStroke.JOIN_ROUND));
                        var path = new java.awt.geom.Path2D.Double();
                        path.moveTo(x.line[0] * N, x.line[1] * N);
                        path.lineTo(x.line[2] * N, x.line[3] * N);
                        path.lineTo(x.line[4] * N, x.line[5] * N);
                        g.draw(path);
                    }
                    k++;
                }
                g.setStroke(new java.awt.BasicStroke(3f));
                for (var runs : walls.values())
                    for (List<double[]> run : runs) {
                        g.setColor(pal[k++ % pal.length]);
                        var path = new java.awt.geom.Path2D.Double();
                        path.moveTo(run.get(0)[0] * N, run.get(0)[1] * N);
                        for (double[] q : run) path.lineTo(q[0] * N, q[1] * N);
                        g.draw(path);
                    }
                javax.imageio.ImageIO.write(im, "png", Paths.get(check, t.id + ".png").toFile());
            }
            System.out.println(t.id + " " + found.values().stream().map(l -> "" + l.size()).reduce((p, q) -> p + " " + q).orElse(""));
        }

        out.append("    )\n\n");
        out.append("    // The centre lines of the walls with a territory on each side, as runs of points (x y, in ten thousandths of a tile)\n");
        out.append("    case class Wall(a : String, b : String, data : $[String]) {\n");
        out.append("        lazy val runs : $[$[(Double, Double)]] = data.map(_.split(' ').toList.filter(_.nonEmpty).map(_.toInt / 10000.0).grouped(2).toList.map(v => (v(0), v(1))))\n");
        out.append("    }\n\n");
        out.append("    val walls : Map[String, $[Wall]] = Map(\n");
        out.append(wallOut);
        out.append("    )\n}\n");
        Files.writeString(nort.resolve("lines.scala"), out.toString());
    }

    static final int CELL = 16;

    // The walls' orange lines: the middles of the orange pixels in each small cell, each given to the wall between
    // the two areas nearest it, chained along the wall from its farthest end and broken at gaps
    static Map<Border, List<List<double[]>>> walls(Tile t, int[] rgb, int[] lab) {
        Map<Border, List<double[]>> found = new LinkedHashMap<>();
        if (!RINGED.contains(t.id))
            for (Border b : t.borders)
                if (b.wall) found.put(b, new ArrayList<>());
        Map<Border, List<List<double[]>>> out = new LinkedHashMap<>();
        if (found.isEmpty())
            return out;

        for (int cy = 0; cy < N; cy += CELL)
            for (int cx = 0; cx < N; cx += CELL) {
                double sx = 0, sy = 0;
                int n = 0;
                for (int y = cy; y < Math.min(N, cy + CELL); y++)
                    for (int x = cx; x < Math.min(N, cx + CELL); x++) {
                        int i = y * N + x;
                        int r = rgb[i * 3], g = rgb[i * 3 + 1], b = rgb[i * 3 + 2];
                        if (r > 200 && g > 90 && g < 175 && b < 90 && r - g > 60) { sx += x + 0.5; sy += y + 0.5; n++; }
                    }
                if (n < 12)
                    continue;
                int px = (int) (sx / n), py = (int) (sy / n);
                double[] near = new double[t.areas.size()];
                Arrays.fill(near, 1e9);
                int rad = 40;
                for (int y = Math.max(0, py - rad); y < Math.min(N, py + rad); y++)
                    for (int x = Math.max(0, px - rad); x < Math.min(N, px + rad); x++)
                        if (lab[y * N + x] >= 0)
                            near[lab[y * N + x]] = Math.min(near[lab[y * N + x]], Math.hypot(x - px, y - py));
                Integer[] order = new Integer[near.length];
                for (int k = 0; k < order.length; k++) order[k] = k;
                Arrays.sort(order, (p, q) -> Double.compare(near[p], near[q]));
                if (order.length < 2 || near[order[1]] > rad)
                    continue;
                String a = t.areas.get(order[0]), b = t.areas.get(order[1]);
                for (Border br : found.keySet())
                    if ((br.a.equals(a) && br.b.equals(b)) || (br.a.equals(b) && br.b.equals(a)))
                        found.get(br).add(new double[] { sx / n / N, sy / n / N });
            }

        for (var e : found.entrySet()) {
            List<double[]> ps = e.getValue();
            if (ps.size() < 4)
                continue;
            List<List<double[]>> runs = new ArrayList<>();
            List<double[]> left = new ArrayList<>(ps);
            while (left.size() >= 4) {
                // From the point farthest from the others' middle, always to the nearest one left, until a gap
                double mx = 0, my = 0;
                for (double[] q : left) { mx += q[0]; my += q[1]; }
                double fx = mx / left.size(), fy = my / left.size();
                double[] cur = Collections.max(left, Comparator.comparingDouble(q -> Math.hypot(q[0] - fx, q[1] - fy)));
                List<double[]> run = new ArrayList<>();
                left.remove(cur);
                run.add(cur);
                while (!left.isEmpty()) {
                    double[] c = cur;
                    double[] next = Collections.min(left, Comparator.comparingDouble(q -> Math.hypot(q[0] - c[0], q[1] - c[1])));
                    if (Math.hypot(next[0] - c[0], next[1] - c[1]) > 2.5 * CELL / N)
                        break;
                    left.remove(next);
                    run.add(next);
                    cur = next;
                }
                if (run.size() >= 4)
                    runs.add(smooth(run));
            }
            if (runs.isEmpty())
                System.err.println(t.id + ": no line for wall " + e.getKey().a + "-" + e.getKey().b);
            else
                out.put(e.getKey(), runs);
        }
        return out;
    }

    // Averaged over neighbours, then every other point
    static List<double[]> smooth(List<double[]> run) {
        List<double[]> s = new ArrayList<>();
        for (int i = 0; i < run.size(); i++) {
            double x = 0, y = 0;
            int n = 0;
            for (int j = Math.max(0, i - 2); j <= Math.min(run.size() - 1, i + 2); j++) { x += run.get(j)[0]; y += run.get(j)[1]; n++; }
            s.add(i == 0 || i == run.size() - 1 ? run.get(i) : new double[] { x / n, y / n });
        }
        List<double[]> out = new ArrayList<>();
        for (int i = 0; i < s.size(); i++)
            if (i % 2 == 0 || i == s.size() - 1) out.add(s.get(i));
        return out;
    }

    static List<Tile> parse() throws IOException {
        List<Tile> list = new ArrayList<>();
        Pattern tp = Pattern.compile("tile\\(\"([^\"]+)\"\\)\\(");
        Pattern ap = Pattern.compile("area\\(\"(\\w+)\", \"(\\w*)\"");
        Pattern bp = Pattern.compile("(border|rough|wall)\\(\"(\\w+)\", \"(\\w+)\"\\)");
        Tile cur = null;
        for (String line : Files.readAllLines(nort.resolve("tiles.scala"))) {
            Matcher m = tp.matcher(line);
            if (m.find() && !line.contains("def tile")) {
                cur = new Tile(m.group(1), new ArrayList<>(), new ArrayList<>());
                list.add(cur);
            }
            if (cur == null)
                continue;
            Matcher a = ap.matcher(line);
            if (a.find() && !line.contains("def area"))
                cur.areas.add(a.group(1));
            Matcher b = bp.matcher(line);
            while (b.find())
                if (!line.contains("def "))
                    cur.borders.add(new Border(b.group(2), b.group(3), b.group(1).equals("wall")));
        }
        return list;
    }

    static boolean[] dashes(int[] a, boolean photo, boolean teal) {
        boolean[] d = new boolean[N * N];
        for (int i = 0; i < N * N; i++) {
            int r = a[i * 3], g = a[i * 3 + 1], b = a[i * 3 + 2];
            int spread = Math.max(r, Math.max(g, b)) - Math.min(r, Math.min(g, b));
            boolean white = r > 180 && g > 200 && b > 195 && spread < 70;
            boolean yellow = r > 190 && g > 150 && b < 120 && r - b > 110 && g - b > 80;
            boolean pale = r > 195 && g > 205 && b < 175 && g - b > 55 && r - b > 40;
            // The photos' white dashes are a light gray, the Wilderness ones a pale blue
            boolean gray = Math.min(r, Math.min(g, b)) > 165 && spread < 70;
            boolean cyan = r > 105 && g > 160 && b > 155 && b - r > 35 && Math.abs(g - b) < 35;
            d[i] = white || yellow || (photo && (pale || gray)) || (teal && cyan);
        }
        return d;
    }

    // 4-connected components, as arrays of pixel indices
    static List<int[]> label(boolean[] d, int[] comp) {
        List<int[]> list = new ArrayList<>();
        Arrays.fill(comp, -1);
        int[] stack = new int[N * N];
        for (int s = 0; s < N * N; s++) {
            if (!d[s] || comp[s] >= 0)
                continue;
            int n = 0, top = 0;
            List<Integer> px = new ArrayList<>();
            stack[top++] = s;
            comp[s] = list.size();
            while (top > 0) {
                int i = stack[--top];
                px.add(i);
                int x = i % N, y = i / N;
                int[] nb = {x > 0 ? i - 1 : -1, x < N - 1 ? i + 1 : -1, y > 0 ? i - N : -1, y < N - 1 ? i + N : -1};
                for (int j : nb)
                    if (j >= 0 && d[j] && comp[j] < 0) { comp[j] = list.size(); stack[top++] = j; }
            }
            list.add(px.stream().mapToInt(Integer::intValue).toArray());
        }
        return list;
    }

    // Centre, main axis and extents of a dash; its centre line through the middles of its two end fifths
    // and its middle fifth, stretched to its ends; its width is its area over its length
    static Dash fit(int[] c) {
        double mx = 0, my = 0;
        for (int i : c) { mx += i % N; my += i / N; }
        mx /= c.length; my /= c.length;
        double sxx = 0, syy = 0, sxy = 0;
        for (int i : c) {
            double dx = i % N - mx, dy = i / N - my;
            sxx += dx * dx; syy += dy * dy; sxy += dx * dy;
        }
        double angle = 0.5 * Math.atan2(2 * sxy, sxx - syy);
        double ux = Math.cos(angle), uy = Math.sin(angle);
        double l0 = 1e9, l1 = -1e9;
        for (int i : c) {
            double l = (i % N - mx) * ux + (i / N - my) * uy;
            l0 = Math.min(l0, l); l1 = Math.max(l1, l);
        }
        double[] sx = new double[3], sy = new double[3];
        int[] n = new int[3];
        for (int i : c) {
            double f = ((i % N - mx) * ux + (i / N - my) * uy - l0) / Math.max(1, l1 - l0);
            int k = f < 0.2 ? 0 : (f >= 0.4 && f < 0.6) ? 1 : f >= 0.8 ? 2 : -1;
            if (k >= 0) { sx[k] += i % N + 0.5; sy[k] += i / N + 0.5; n[k]++; }
        }
        double[] p = new double[6];
        for (int k = 0; k < 3; k++) {
            p[k * 2] = n[k] > 0 ? sx[k] / n[k] : mx + 0.5;
            p[k * 2 + 1] = n[k] > 0 ? sy[k] / n[k] : my + 0.5;
        }
        // The end fifths' middles are a tenth of the length in from the ends
        for (int e = 0; e < 3; e += 2) {
            double dx = p[e * 2] - p[2], dy = p[e * 2 + 1] - p[3];
            double d = Math.hypot(dx, dy);
            double grow = d > 0 ? (d + 0.1 * (l1 - l0 + 1)) / d : 1;
            p[e * 2] = p[2] + dx * grow;
            p[e * 2 + 1] = p[3] + dy * grow;
        }
        double length = Math.hypot(p[2] - p[0], p[3] - p[1]) + Math.hypot(p[4] - p[2], p[5] - p[3]);
        double width = c.length / Math.max(1, length);
        for (int k = 0; k < 6; k++) p[k] /= N;
        return new Dash((mx + 0.5) / N, (my + 0.5) / N, angle, length / N, width / N, p);
    }

    // In order along the border: from one end of the farthest pair, always to the nearest left
    static List<Dash> chain(List<Dash> all) {
        // Light patches taken for a dash are off the road: away from the others, or across the way to the nearest
        List<Dash> ds = new ArrayList<>();
        for (Dash p : all) {
            Dash q = all.stream().filter(o -> o != p).min(Comparator.comparingDouble(o -> gap(p, o))).orElse(null);
            if (all.size() < 4 || (q != null && gap(p, q) < 0.035 && along(p, q) > Math.cos(Math.toRadians(40))))
                ds.add(p);
        }
        if (ds.size() < 3)
            return ds;
        Dash start = null;
        double far = -1;
        for (Dash p : ds)
            for (Dash q : ds) {
                double d = dist(p, q);
                if (d > far) { far = d; start = p; }
            }
        List<Dash> left = new ArrayList<>(ds);
        List<Dash> out = new ArrayList<>();
        Dash cur = start;
        left.remove(cur);
        out.add(cur);
        while (!left.isEmpty()) {
            Dash c = cur;
            Dash next = Collections.min(left, Comparator.comparingDouble(q -> dist(c, q)));
            left.remove(next);
            out.add(next);
            cur = next;
        }
        return out;
    }

    static double dist(Dash p, Dash q) { return Math.hypot(p.x - q.x, p.y - q.y); }

    // How much the way from p to q follows p (the cosine of the angle between them)
    static double along(Dash p, Dash q) {
        double ax = p.line[4] - p.line[0], ay = p.line[5] - p.line[1], bx = q.x - p.x, by = q.y - p.y;
        return Math.abs(ax * bx + ay * by) / Math.max(1e-9, Math.hypot(ax, ay) * Math.hypot(bx, by));
    }

    // Between the nearest ends of two dashes
    static double gap(Dash p, Dash q) {
        double g = 1e9;
        for (int i = 0; i < 6; i += 4)
            for (int j = 0; j < 6; j += 4)
                g = Math.min(g, Math.hypot(p.line[i] - q.line[j], p.line[i + 1] - q.line[j + 1]));
        return g;
    }

    static int[] readRaw(Path file, String kind, int channels) throws Exception {
        List<String> cmd = new ArrayList<>(List.of("convert", file.toString()));
        if (kind.equals("alpha"))
            cmd.addAll(List.of("-alpha", "extract"));
        else
            cmd.addAll(List.of("-background", "black", "-alpha", "remove"));
        cmd.addAll(List.of("-resize", N + "x" + N + "!", "-depth", "8", (kind.equals("alpha") ? "gray:-" : "rgb:-")));
        Process p = new ProcessBuilder(cmd).redirectError(ProcessBuilder.Redirect.INHERIT).start();
        byte[] b = p.getInputStream().readAllBytes();
        if (p.waitFor() != 0 || b.length != N * N * channels)
            throw new IOException("can't read " + file);
        int[] v = new int[b.length];
        for (int i = 0; i < b.length; i++) v[i] = b[i] & 0xff;
        return v;
    }

    static void writeRaw(Path file, int[] rgb) throws Exception {
        Process p = new ProcessBuilder("convert", "-size", N + "x" + N, "-depth", "8", "rgb:-", file.toString()).redirectError(ProcessBuilder.Redirect.INHERIT).start();
        byte[] b = new byte[rgb.length];
        for (int i = 0; i < b.length; i++) b[i] = (byte) rgb[i];
        try (OutputStream o = p.getOutputStream()) { o.write(b); }
        p.waitFor();
    }
}
