// Makes nort/icons.scala: where the resource icons (and lore stones) are on each tile, so the map
// keeps the warchiefs, Kaija and creatures off them and draws them over any piece that still overlaps.
//
// tile-masks.py cuts the resource icons out of the territory masks (webp2/nort/images/tile/mask/),
// so an icon is a hole that no area's mask covers. Each hole of icon size is stored as a circle
// (centre and radius, in tile units) around it; bigger ones (the Great Lake) are left out.
//
// Needs Java 11+ and ImageMagick (convert). Run from the repository root:
//   java haunt-roll-fail/nort/tools/ResourceIcons.java

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.regex.*;

public class ResourceIcons {
    static final int N = 237;
    // Icons the masks don't cut out (tinted with their territory, so only kept clear, not drawn on top):
    // the wood on the Wilderness peaks
    static final Map<String, String> EXTRA = Map.of(
        "wild-peaks-1", "Icon(0.540, 0.165, 0.070)",
        "wild-peaks-2", "Icon(0.540, 0.165, 0.070)");

    public static void main(String[] args) throws Exception {
        Path root = Paths.get("haunt-roll-fail").toAbsolutePath();
        Path nort = root.resolve("nort");
        Path masks = root.resolve("webp2/nort/images/tile/mask");

        StringBuilder out = new StringBuilder();
        out.append("package nort\n//\n//\n//\n//\nimport hrf.colmat._\n//\n//\n//\n//\n\n");
        out.append("// Generated by nort/tools/ResourceIcons.java from the territory masks; do not edit by hand.\n");
        out.append("// The resource icons on each unturned tile: centre and radius, in tile units.\n");
        out.append("object TileIcons {\n");
        out.append("    case class Icon(x : Double, y : Double, r : Double)\n\n");
        out.append("    val icons : Map[String, $[Icon]] = Map(\n");

        Map<String, List<String>> tiles = parse(nort.resolve("tiles.scala"));
        List<String> rows = new ArrayList<>();

        for (var e : tiles.entrySet()) {
            int[] sum = new int[N * N];
            for (String a : e.getValue()) {
                int[] v = readAlpha(masks.resolve(e.getKey() + "-" + a + ".webp"));
                for (int i = 0; i < N * N; i++) sum[i] += v[i];
            }

            boolean[] hole = new boolean[N * N];
            for (int i = 0; i < N * N; i++) hole[i] = sum[i] < 128;

            List<String> icons = new ArrayList<>();
            int[] seen = new int[N * N];
            for (int s = 0; s < N * N; s++) {
                if (!hole[s] || seen[s] != 0) continue;
                List<Integer> px = new ArrayList<>();
                Deque<Integer> q = new ArrayDeque<>(List.of(s));
                seen[s] = 1;
                while (!q.isEmpty()) {
                    int i = q.pop();
                    px.add(i);
                    int x = i % N, y = i / N;
                    for (int[] d : new int[][] { { 1, 0 }, { -1, 0 }, { 0, 1 }, { 0, -1 } }) {
                        int nx = x + d[0], ny = y + d[1];
                        if (nx < 0 || ny < 0 || nx >= N || ny >= N) continue;
                        int j = ny * N + nx;
                        if (hole[j] && seen[j] == 0) { seen[j] = 1; q.push(j); }
                    }
                }
                // An icon is about a tenth of the tile across; specks and the lake are not icons
                if (px.size() < 40 || px.size() > 2500) continue;
                double cx = 0, cy = 0;
                for (int i : px) { cx += i % N + 0.5; cy += i / N + 0.5; }
                cx /= px.size(); cy /= px.size();
                double r = 0;
                for (int i : px) r = Math.max(r, Math.hypot(i % N + 0.5 - cx, i / N + 0.5 - cy));
                icons.add(String.format(Locale.ROOT, "Icon(%.3f, %.3f, %.3f)", cx / N, cy / N, (r + 0.5) / N));
            }

            if (EXTRA.containsKey(e.getKey()))
                icons.add(EXTRA.get(e.getKey()));

            rows.add("        \"" + e.getKey() + "\" -> $(" + String.join(", ", icons) + ")");
            System.out.println(e.getKey() + " " + icons);
        }

        out.append(String.join(",\n", rows)).append("\n    )\n}\n");
        Files.writeString(nort.resolve("icons.scala"), out.toString());
    }

    static Map<String, List<String>> parse(Path file) throws IOException {
        Map<String, List<String>> tiles = new LinkedHashMap<>();
        Pattern tp = Pattern.compile("tile\\(\"([^\"]+)\"\\)\\(");
        Pattern ap = Pattern.compile("area\\(\"(\\w+)\", \"(\\w*)\"");
        List<String> cur = null;
        for (String line : Files.readAllLines(file)) {
            Matcher m = tp.matcher(line);
            if (m.find() && !line.contains("def tile"))
                tiles.put(m.group(1), cur = new ArrayList<>());
            Matcher a = ap.matcher(line);
            if (cur != null && a.find() && !line.contains("def area"))
                cur.add(a.group(1));
        }
        return tiles;
    }

    static int[] readAlpha(Path file) throws Exception {
        Process p = new ProcessBuilder("convert", file.toString(), "-alpha", "extract", "-resize", N + "x" + N + "!", "-depth", "8", "gray:-").redirectError(ProcessBuilder.Redirect.INHERIT).start();
        byte[] b = p.getInputStream().readAllBytes();
        if (p.waitFor() != 0 || b.length != N * N)
            throw new IOException("can't read " + file);
        int[] v = new int[b.length];
        for (int i = 0; i < b.length; i++) v[i] = b[i] & 0xff;
        return v;
    }
}
